services:
  db:
    image: postgres:15
    container_name: gonzo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gonzo
    ports:
      - "5433:5432"
    volumes:
      - gonzo_data:/var/lib/postgresql/data

volumes:
  gonzo_data: